### ISSUE TITLE
Document exit codes

### ISSUE THREAD

**Issue by di** [trailofbits/pip-audit#150]
We should document `pip-audit`'s current exit code behavior.

(ref: https://twitter.com/lostgen/status/1466143595841400838)

**Comment by Lewiscowles1986** [comment]
So I'd be interested in contributing to this. I also "have ideas" about nice to have features if exit-codes matter. 

1. Suppress exit codes with a flag, so that orgs and projects can gain visibility and plan, without breaking their pipelines.
    Big picture, this is a giant except wrapping __main__, with the least helpful error being "Something unexpected occurred" to STDOUT or STDERR, but still returning a zero exit code if the flag to supress exit codes is active.

2. Sadly with exit codes and deliberate pipeline breaks, comes the need to be able to exclude, or allow vulns. Maybe there is no known fix and you're not able to, or in an org that can or will fix.

I Think without the above two features;

**Comment by woodruffw** [comment]
Addressed in #201.

Longer term, we could probably diversify our exit codes to include distinct codes for e.g. `--strict` failing.

**Comment by di** [comment]
> Suppress exit codes with a flag, so that orgs and projects can gain visibility and plan, without breaking their pipelines.
Big picture, this is a giant except wrapping main, with the least helpful error being "Something unexpected occurred" to STDOUT or STDERR, but still returning a zero exit code if the flag to supress exit codes is active.

I'm not sure the ability to suppress exit codes is something we need/want to support here, as this can trivially be done with an invocation like `pip-audit | true` (at least, on Unix systems).

Besides the need to run `pip-audit`, but not fail a CI pipeline, is there another reason why we need this?

> Sadly with exit codes and deliberate pipeline breaks, comes the need to be able to exclude, or allow vulns. Maybe there is no known fix and you're not able to, or in an org that can or will fix.

Let's open a separate issue to track this.

**Comment by woodruffw** [comment]
That's a fair point. I can amend #201 to only update our documentation, rather than adding an additional flag.
