### ISSUE TITLE
Document `pip-audit`'s security model

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pip-audit#181]
The distinction between `pip-audit` and `pip-audit -r <INPUT>` might lead some people to believe that the latter is a security boundary, i.e. something you can safely run when you don't trust your packages.

This isn't true (and can't be true, for dependency resolution reasons), so we should document exactly what `pip-audit`'s security model and guarantees are. In particular, we should make sure people understand that running `pip-audit -r ...` is **roughly equivalent** to running `pip install -r ...`.

Ref: https://github.com/trailofbits/pip-audit/issues/180#issuecomment-985818011

**Comment by matthewdeanmartin** [comment]
I just learned about  export `PIP_ONLY_BINARY=:all:` and  `--only-binary=:all:` which is the safe way to install an untrusted package (if it comes in a wheel format). I haven't checked to figure out if the env works with pip-audit.

Does pip-audit run an `import` on the code in a package, like the way `pydoc` does? Or does it just run setup.py when there is no wheel?

**Comment by tetsuo-cpp** [comment]
> Does pip-audit run an `import` on the code in a package, like the way `pydoc` does? Or does it just run setup.py when there is no wheel?

It only runs `setup.py` in the case where there isn't a wheel available. The wheel format contains a metadata file which should list its dependencies so in that case, it's a lot simpler since we can just read that. Relevant code [here](https://github.com/trailofbits/pip-audit/blob/main/pip_audit/_dependency_source/resolvelib/pypi_provider.py#L116).
