### ISSUE TITLE
Support `--dry-run` with the `--fix` flag

### ISSUE THREAD

**Issue by tetsuo-cpp** [trailofbits/pip-audit#220]
Ideally, users should be able to run `--fix` with `--dry-run` and find out what changes would be applied without actually modifying the environment/requirements file.

**Comment by woodruffw** [comment]
This is an interesting case, since it changes the functionality of `--dry-run` w/r/t the `Auditor` object:

* `pip-audit --dry-run`: resolve dependencies, but do not audit them
* `pip-audit --fix --dry-run`: resolve dependencies and audit them, but do not attempt to fix them

Not a difficult change to make, but I'll give some thought to how we describe that behavior in the `--help` and README.
