### ISSUE TITLE
Verify hashes with PyPI when using OSV as a vulnerability service

### ISSUE THREAD

**Issue by tetsuo-cpp** [trailofbits/pip-audit#234]
At the moment, we only verify hashes with using PyPI as the vulnerability service. If we use OSV, we should still query PyPI for the purpose of verifying hashes.

**Comment by woodruffw** [comment]
We should put some thought into how we want to do this, since it involves (worst case) doubling the number of network round-trips we do.

In the mean time, we should probably add a warning that tells users that `--require-hashes -s osv` only enforces hash *presence*, not hash *validity.* OTOH maybe that's not a serious issue, since `pip install` will completely refuse to install things with wrong hashes anyways?

**Comment by tetsuo-cpp** [comment]
Yeah that's a good point. Maybe it's best to just warn and consider this done.

**Comment by woodruffw** [comment]
Yeah, let's go with that for now.
