### ISSUE TITLE
Exempt editable packages 

### ISSUE THREAD

**Issue by ehennenfent** [trailofbits/pip-audit#237]
**Is your feature request related to a problem? Please describe.**

We use `pip-audit` in the Manticore CI to check for security issues in our dependencies. This is fine for most of our development, but when we try to create a new release of Manticore, `pip-audit` fails. The problem is that the release PR we're trying to check contains an incremented version number, but that version of Manticore hasn't been published on PyPI yet, so `pip-audit` can't check it for issues.
[Example](https://github.com/trailofbits/manticore/runs/4940375032?check_suite_focus=true)

**Describe the solution you'd like**

Locally installed packages should be ignored when checking for security issues, since they may not have been published on PyPI. 

**Describe alternatives you've considered**

I looked at removing the `--strict` flag, but this seems like a poor choice for running in a CI environment. The `--local` flag seems to make `pip-audit` _only_ look at local packages. 

**Additional context**
The relevant lines from our `ci.yml`:
```
    - name: Run pip-audit
      run: |
        python -m pip install .
        pip-audit --strict --desc
```

**Comment by tetsuo-cpp** [comment]
> The --local flag seems to make pip-audit only look at local packages.

The `--local` flag controls whether to only audit packages that have been installed in the current virtual environment (that is, local packages) or to include globally installed packages (often things like `virtualenv`, `wheel`, `setuptools`, etc). So that type of local/global distinction won't help us here.

> #### Describe the solution you'd like
> Locally installed packages should be ignored when checking for security issues, since they may not have been published on PyPI.

That'd be straightforward to achieve I think. For local installations, `pip-api` will fill in a `location` on the file system. So we can just check whether that is populated.

The only thing is that we'll miss reporting some vulnerabilities for packages that have been published to PyPI and just happen to have been installed by `pip install .`

We could also solve this issue by allowing projects to supply configuration that whitelists certain packages (more on that at https://github.com/trailofbits/pip-audit/issues/209).

@woodruffw @di What do you think about this?

**Comment by woodruffw** [comment]
> That'd be straightforward to achieve I think. For local installations, `pip-api` will fill in a `location` on the file system. So we can just check whether that is populated.

That makes sense to me, although the edge case you pointed out with `pip install .` is concerning -- I suspect that pattern is pretty common and that we'll end up skipping much of many audits that way.

I think #209 is looking the most appealing to me: at the most general this issues is a variant of all of the other "I want to skip some packages" issues.

**Comment by di** [comment]
I think we maybe need a little more context here:

> We use `pip-audit` in the Manticore CI to check for security issues in our dependencies.

These are sub-dependencies of `manticore`, or something else? Dev dependencies in a requirements file?

Assuming they're sub-dependencies of `manticore`, the effect of skipping an audit of `manticore` would have the effect of skipping all its potential sub-dependencies as well (since `pip-audit` would skip resolution for `manticore`), which I think would make the audit somewhat useless.

Ultimately I think https://github.com/trailofbits/pip-audit/issues/81 is what you actually want here: you don't care about vulnerabilities in the top-level `manticore` project, because you're working with a version that hasn't been released yet. But you care about the sub-dependencies that may get installed when this source tree is installed.

**Comment by woodruffw** [comment]
> These are sub-dependencies of `manticore`, or something else? Dev dependencies in a requirements file?

@ehennenfent can confirm, but I believe it's manticore's sub-dependencies.

**Comment by ehennenfent** [comment]
This is correct; we want to audit _only_ the packages Manticore depends on, and not Manticore itself. #81 would work for our purposes. I wouldn't mind having an option to ignore packages installed via `pip install -e <directory>`, but if that's out of scope for `pip-audit`, we can close in favor of #81.

**Comment by di** [comment]
I'll leave this open to track whether we want to exempt _editible_ packages (and have updated the title accordingly).

**Comment by woodruffw** [comment]
Opened #244 to explore implementing this.
