### ISSUE TITLE
Feature:  --best-effort for --no-deps -r requirements.txt

### ISSUE THREAD

**Issue by jaytmiller** [trailofbits/pip-audit#315]
**Is your feature request related to a problem? Please describe.**

Yes.  Having --no-deps crash on the first dependency with no hash is too pessimistic for us.   Although my project generally compiles requirements.txt for all dependencies to exact x.y.z pypi versions or hashes,  occasionally packages in rapid development appear unpinned even in requirements.txt.    We need --no-deps because resolving all requirements dynamically (if it works) requires 20-30 min.

**Describe the solution you'd like**

It'd be nice to have a --best-effort option which ignores unpinned/hashless requirements instead of aborting the entire check when running with --no-deps. 

**Describe alternatives you've considered**

For us,  some info is better than no info,  both Dependabot and Safety handle the same situation gracefully.   Increasingly though,  for us,  neither will be free,  so I'm looking for alternatives.

**Comment by woodruffw** [comment]
Thanks for filing the request!

I'm personally inclined against this feature, for two reasons:

* Consistency with `pip`'s behavior: `pip` (and all other packaging tools in Python) treat the presence of a hash as a *mandatory* signal for hash-checking mode, meaning that the presence of an unhashed dependency is always an error. `pip-audit` strives to maintain behavioral compatibility with `pip`, both to match user expectations *and* because we intend to eventually upstream `pip-audit` into `pip` as `pip audit`.

* There are mature open-source tools that address this problem (maintaining both unhashed and hashed dependency trees simultaneously). For example, [Warehouse](https://github.com/pypi/warehouse) (the PyPI codebase) tracks both [here](https://github.com/pypi/warehouse/tree/main/requirements) using [`pip-compile`](https://github.com/jazzband/pip-tools). 

In your case (an extremely long dependency resolution process), the best approach is probably to have a fully-pinned, human maintained set of `requirements.in` inputs *and* an automation-maintained fully-hashed `requirements.txt` output produced via `pip-compile` on `requirements.in`. That should accomplish everything you need: you'll be able to run with `--no-deps` on `requirements.in` (since it's fully pinned), and you'll be able to set your CI to run on the fully hashes `requirements.txt` whenever it's automatically updated.

**Comment by jaytmiller** [comment]
Thanks anyway,  looking forward to `pip audit`!
