### ISSUE TITLE
How should the sdist/wheel distinction be handled and communicated?

### ISSUE THREAD

**Issue by aragilar** [trailofbits/pip-audit#358]
First, pip-audit is a really good idea, and I'm going to look at how best to start using it in projects I work on. The python community needs this kind of tooling, so thank you for developing and maintaining this. However, I can see a major problem with pip-audit, in that it seems to assume that a vulnerability is tied to a specific package and version, rather than a specific artefact. This has issues where wheels bundle other, non-Python libraries, and where vulnerabilities in those libraries affect only the pre-compiled wheels, or even only a subset of the pre-compiled wheels. Assuming python package `A` bundles vulnerable version of non-Python library `B` in its wheel, then given an environment with `A`, pip-audit currently appears to have two options:
 * Tell the user package `A` is vulnerable, even if vulnerable version of `B` is not used (e.g. a fixed version of `B` is installed by another tool such as conda, or `B` can be replaced by `C` which is API compatible with `B` but does not share `B`'s vulnerability). This would result in a "pip-audit cries woof" situation like npm audit, which means people ignore pip-audit. It would also likely increase the pip vs conda division.
 * Do not tell the user package `A` is vulnerable, people find out pip-audit did not tell them that they installed a vulnerable artefact, and complain "pip" does not work (and ecosystem Y is better).

Neither of these seem ideal, and I can't see a way around them as long as sdists and wheels have the same version number (having different version numbers is a way to resolve a related issue around distribution-packaged versions where a fix has been applied), or somehow the vulnerabilities are tied to artefacts. I suspect the best current solution would be to have clear documentation around what pip-audit does in such cases, and what users can do to avoid hitting this issue (e.g. what other audit tools can be used to complement pip-audit).

**Comment by woodruffw** [comment]
Thanks a ton for the detailed comment, and the kind words as a potential user!

Yeah, this is a conceptual issue with the packaging data model in Python (and some other packaging ecosystems): a specifier like `foo==1.2.3` can be satisfied by one or more "candidates", which in turn may or may not actually have anything to do with each other (the implicit contract with package names is that they do, but that's not a formal guarantee that we can make).

Python "solves" this problem by hiding candidate selection semantics, meaning that an end user (who may have a different interpreter, etc.) can't be assumed to select the same candidate for `foo==1.2.3` as `foo`'s developer. That incentivizes developers to make their distribution files (which form candidates) as consistent as possible.

Another layer of complexity happens with distributors, like you mentioned: a non-PyPI distributor of `foo==1.2.3` might decide to patch out a vulnerability that's still present in the PyPI release, without bumping the version. `pip-audit` fundamentally can't handle this case with the current packaging metadata. It's possible that a future PEP could specify additional packaging metadata that allows a distribution to note that it's a patched version of a pre-existing distribution, but I'm not sure if the community would be receptive to that (since it undermines unique versioning).

Ultimately, I agree that these are issues. But absent evidence of them actually causing trouble for most users (resulting in the fatigue that happens with `npm audit`), I'm inclined to say that they're not serious problems for `pip-audit`: most sdist/wheel distributions of the same release *should* have the same vulnerability, if only because of the invisible candidate selection behavior mentioned above.

The exception to that is wheels that vendor non-Python libraries: it's conceivable that a vulnerability would only apply to wheels of `foo==1.2.3` that include `libfoo.so`, whereas the sdist *might* be safe because it links to the system `libfoo.so` instead. But cases like those are currently out of scope for the PyPA advisory DB itself: the goal (as I understand it) is to track **just** Python vulnerabilities, not native vulnerabilities that happen to be exposed to Python. This is the same decision that the RUSTSEC DB makes, and I believe it's the (de facto) policy of `npm audit` and most other language-specific package auditing tools.

So, TL;DR: for the time being, `pip-audit` will not (and can't meaningfully) make a distinction between sdist and wheel distributions of the same version, since (1) the case where it matters for vulnerability reporting is out of scope of the data source we use, and (2) candidate selection in `pip` acts as a "forcing function" for consistency that should make other cases extremely rare.

**Comment by aragilar** [comment]
Yep, I don't see this being an issue in the near term (or at least I'm not aware of it being an issue currently for anyone, and hopefully maintainers are taking action to make this a non-issue), and the pure-python approach to tracking vulnerabilities makes sense (and I agree is the right one to take).

I raised this more to get it on the radar, as I suspect this issue would impact different parts of the Python ecosystem to different degrees. For the "web" part, libraries are more commonly pure python, or using C-extensions for speedups (at least based on the libraries I've used), and there's some level of awareness of security. For the "data science" community, there are a lot more projects which wrap and bundle non-Python libraries, and people generally ignore or are ignorant of the issues.

An example of this (which is a thankfully a non-example because the maintainers (of which I'm one) thought about this, but I can see this happening with other libraries) is h5py: h5py wraps the HDF5 library which reads HDF5 files. One feature of the HDF5 library is to read data stored on S3 compatible data stores, for which is uses libcurl. The wheels that h5py upload to PyPI include a build of HDF5 without the S3 support, as that would require also including libcurl (and we don't have the bandwidth to keep up with libcurl CVEs). I wouldn't expect pip-audit to pick up that a older wheel has an old libcurl, but it might be worth having some wording in the docs somewhere (maybe https://github.com/trailofbits/pip-audit#security-model) to make users aware of this issue (I'm happy to create a PR if you think that might be helpful).

**Comment by woodruffw** [comment]
> I raised this more to get it on the radar, as I suspect this issue would impact different parts of the Python ecosystem to different degrees. For the "web" part, libraries are more commonly pure python, or using C-extensions for speedups (at least based on the libraries I've used), and there's some level of awareness of security. For the "data science" community, there are a lot more projects which wrap and bundle non-Python libraries, and people generally ignore or are ignorant of the issues.

Yep, this is a good goal, and a good observation -- my (very limited) experience with ML folks indicates that security awareness among them is similarly limited.

+1 on updating the documented security model to emphasize that `pip-audit` doesn't attempt to "trawl" native dependencies for non-Python vulnerabilities. There was some verbiage that @di or myself used in a previous issue discussing this that I liked, so I'll try to find it and add it (and tag for you feedback!).
