### ISSUE TITLE
`pip-audit` sometimes fails to write to the `pip` HTTP cache

### ISSUE THREAD

**Issue by tetsuo-cpp** [trailofbits/pip-audit#93]
I'm pretty sure this was working before, so not sure what changed. But I'm seeing this error when running `pip-audit`.
```
WARNING:pip_audit.service.pypi:Failed to write to cache directory, performance may be degraded: [Errno 17] File exists: '/Users/tetsuo/Library/Caches/pip/http/a/8/5/2/2/tmpwca4e31a' -> '/Users/tetsuo/Library/Caches/pip/http/a/8/5/2/2/a8522f9c472311479fe3f5601fa0a00281eca929981e997fa313e68c'
```

**Comment by woodruffw** [comment]
I might be misunderstanding how the cache works, but this looks fishy:

```python
        with NamedTemporaryFile(dir=os.path.dirname(name)) as f:
            f.write(value)
            os.link(f.name, name)
```

I believe `NamedTemporaryFile` will call `unlink(f)` as soon as the context closes, so the cache as-is is currently a no-op that leaves a broken link from `f.name` to `name`. Then, it probably tries to re-cache the same thing and there's now a broken link in place, so the `os.link` call fails.

So, I think the fix(es) here are to avoid the context manager, and maybe use `rename` instead (since it's also atomic, and has fewer failure modes).

**Comment by woodruffw** [comment]
(Using `rename` will also be consistent with `pip`'s behavior, which uses `os.replace` internally and the latter is implemented via `rename(2)`).
